server:
  port: 8081
spring:
  application:
    name: AuthProvider #服务名称
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_netpacket?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml

#自定义属性
npacket:
  passkey: xqCWdZwKIJrlCUekvYxqSA==  #密码对应的密钥
  redis:
    host: 39.105.189.141
    port: 6380
    psw: qfjava
