server:
  port: 8097
spring:
  application:
    name: SkillApi
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


