
server:
  port: 8087
spring:
  application:
    name: SkillProvider #服务名称
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_netpacket?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 39.105.189.141
    port: 5672
    username: guest
    password: guest
    virtual-host: /  #虚拟主机路径

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

npacket:
  redis:
    host: 39.105.189.141
    port: 6380
    psw: qfjava
  http:
    limiter: 1000 #自定义属性 请求上限 每秒
  url:
    aeskey1: akiDQxNUQBjL7C8ZeY4OvA==
    aeskey2: K7ESwS1wvIqta4FN2lr+oQ==