server:
  port: 8080
spring:
  application:
    name: ZuulApi #服务名称

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    userauth:
      path: /auth/**  #外界的请求路径 url
      serviceId: AuthApi  #要转发到的服务名称
    outnet:
      path: /outnet/**
      serviceId: OutNetApi
    search:
      path: /search/**
      serviceId: SearchApi
    user:
      path: /user/**
      serviceId: UserApi