server:
  port: 8092
spring:
  application:
    name: OutNetApi
  main:
    allow-bean-definition-overriding: true
    #设置单个文件大小，单位MB和KB都可以
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


